name: Deploy Liquibase (Manual)

on:
  workflow_dispatch:

jobs:
  update-banco:
    runs-on: self-hosted

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Diagnóstico de rede até o SQL
        shell: powershell
        run: |
          Write-Host "Testando conexão TCP até o SQL..."
          Test-NetConnection localhost -Port 1433 | Format-List *

      - name: Executar Liquibase
        shell: powershell
        run: |
          & "C:\Liquibase\liquibase.bat" `
            --search-path="." `
            --changelog-file="db-master.xml" `
            --url="jdbc:sqlserver://${{ secrets.DB_HOST }};databaseName=${{ secrets.DB_NAME }};trustServerCertificate=true" `
            --username="${{ secrets.DB_USER }}" `
            --password="${{ secrets.DB_PASSWORD }}" `
            update

      - name: Marcar tag pós-deploy
        shell: powershell
        run: |
          $tag = "deploy_$(Get-Date -Format 'yyyyMMdd_HHmmss')"
          Write-Host "Marcando tag $tag"
          & "C:\Liquibase\liquibase.bat" `
            --search-path="." `
            --changelog-file="db-master.xml" `
            --url="jdbc:sqlserver://${{ secrets.DB_HOST }};databaseName=${{ secrets.DB_NAME }};trustServerCertificate=true" `
            --username="${{ secrets.DB_USER }}" `
            --password="${{ secrets.DB_PASSWORD }}" `
            tag $tag
