name: Rollback por Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag para a qual deseja voltar (ex.: deploy_costdrivers_20260501_121355)'
        required: true

jobs:
  rollback-to-tag:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Executar Rollback para Tag
        shell: powershell
        run: |
          & "C:\Liquibase\liquibase.bat" `
            --search-path="." `
            --changelog-file="db-master.xml" `
            --url="jdbc:sqlserver://${{ secrets.DB_HOST }};databaseName=${{ secrets.DB_NAME }};trustServerCertificate=true" `
            --username="${{ secrets.DB_USER }}" `
            --password="${{ secrets.DB_PASSWORD }}" `
            rollback --tag=${{ github.event.inputs.tag }}